#!/bin/sh
set -eu

LISTEN_PORT="${STUBBY__LISTEN_PORT:-53}"
LOG_LEVEL="${STUBBY__LOG_LEVEL:-GETDNS_LOG_ERR}"
IDLE_TIMEOUT="${STUBBY__IDLE_TIMEOUT:-10000}"
EDNS_CLIENT_SUBNET_PRIVATE="${STUBBY__EDNS_CLIENT_SUBNET_PRIVATE:-1}"
ROUND_ROBIN_UPSTREAMS="${STUBBY__ROUND_ROBIN_UPSTREAMS:-0}"
TEMPLATE="/etc/stubby/stubby.yml.template"
CONF="/etc/stubby/stubby.yml"

sed \
  -e "s/__LISTEN_PORT__/${LISTEN_PORT}/g" \
  -e "s/__LOG_LEVEL__/${LOG_LEVEL}/g" \
  -e "s/__IDLE_TIMEOUT__/${IDLE_TIMEOUT}/g" \
  -e "s/__EDNS_CLIENT_SUBNET_PRIVATE__/${EDNS_CLIENT_SUBNET_PRIVATE}/g" \
  -e "s/__ROUND_ROBIN_UPSTREAMS__/${ROUND_ROBIN_UPSTREAMS}/g" \
  "${TEMPLATE}" > "${CONF}"

exec stubby -C "${CONF}" -l
